#!/bin/bash

echo 'Current system time: '
date;
echo
echo 'System uptime: '
uptime;
echo
echo '--------------------------------------------------------------------'
echo
echo 'Currently connected: '
echo
who;
echo
echo '--------------------------------------------------------------------'
echo
echo 'last connections: '
echo
last -a | head -4
echo
echo '--------------------------------------------------------------------'
echo
echo 'Disk / Memory usage: '
echo
df -h | xargs | awk '{print "Free/total disk: " $11 " / " $9}'
free -m | xargs | awk '{print "Free/total memory: " $17 " / " $8 " MB"}'
echo
echo '--------------------------------------------------------------------'
echo
echo 'Utilization :'
top -b |head -3
echo`

